# Generated by Django 3.1.6 on 2021-02-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210203_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologie',
            name='docs',
            field=models.CharField(default='Google It', max_length=250),
        ),
    ]
