# Generated by Django 3.1.6 on 2021-02-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='build_stat',
            field=models.CharField(choices=[('B', 'Built'), ('NB', 'Not Built')], default='NB', max_length=2),
        ),
    ]
