# Generated by Django 3.1.6 on 2021-02-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20210204_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='creator',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
