# Generated by Django 3.1.6 on 2021-02-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_app_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='creator',
            field=models.IntegerField(max_length=100),
        ),
    ]
