# Generated by Django 3.1.6 on 2021-02-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20210205_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='creator',
            field=models.IntegerField(),
        ),
    ]
