# Generated by Django 3.1.6 on 2021-02-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20210205_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.TextField(default='main_app/static/images/Anonymous_emblem.svg.png'),
        ),
        migrations.AlterField(
            model_name='technologie',
            name='docs',
            field=models.CharField(default='https://google.com/', max_length=250),
        ),
    ]
