# Generated by Django 3.1.6 on 2021-02-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20210208_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.TextField(default='https://t4america.org/wp-content/uploads/2016/10/Blank-User.jpg'),
        ),
    ]
